version: '2.2'
services:
  devstation:
    build: .
    ports:
      - "22:22"
      - "5900:5900"
    restart: always
    networks:
      devstation:
        ipv4_address: 10.6.66.2
    mac_address: 02:42:ac:60:80:04
    hostname: devstation
    user: apps
    privileged: true
    environment:
      VNC_SERVER_PASSWORD: Change123!
    volumes:
      - ./home:/home/apps
      - type: bind
        source: ./fortivpn.conf
        target: /etc/openfortivpn/config
    # mem_limit: "512m"
    # memswap_limit: "512m"
    # cpus: 0.5
    logging:
      options:
        max-size: 50m
networks:
  devstation:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.6.66.0/24
    